language: python
python:
- '3.4'
install: pip install tox-travis codecov==2.0.5
script: tox
deploy:
  provider: pypi
  user: sallyruthstruik
  password:
    secure: RsR6rhOkkrDBqlSM8G3Ctf//AAR1Ml1ibmZmp2rlFBRmL0d/ekQfDfTdABycdW+Qacz/bZmRsobggVZHKBHMvzNSQ/GbxzGEOvSH+GAaAZpyaWjERetWoTVHiT8+mWFi2cT93G18M7gtmdUITJ4/dxtk7CptRx74mi7775kQ6uEOnWr3Pxq16//Qq4Qmmce9+OMZxKixh59ayMG4EE3NnQz11K0zVcvZclHlG0fO5akhVcG5ZRmE2rm9fle62+BunG2rMjasUg5+CNvsf4PodObX6RSy+DKiyhKCO3ofreccN6lwyal0DlxwvuNaEHwOC5L7u2/118nnCVi4DDL6+DDzIExIAQMOSydHL5k5Eta7c84sVG+JNmv2XbUj26davN3hD1orRdL8efCqu6MeGz8rx1sft8azwnQWbvd5IFLgB2LT5Eo2LCQeSSJcmKlL6Ux7FthmtKm3DUKfI8uTDD2RrAqjL9aTSvXqajLXVftBxoWb2aYRNbA1pXuu37mK9egRf7AGFPq/tJv8gKqmMYJtc/UpAEbn2y9ipqDNMorztSYo9Xf+Q90QjqUjNzOP90qJek5tlIot8mxF9QVTz8p8vzt1u1PCXJX/hZMZCnFLrMmHNCTa1BlfSDhHAE6qh/WP88z3wHBC5045ba5dL4Asg/1n1Fp3pwSUDGDtXYs=
after_success:
- codecov
